(setq i 0)
(loop (if (= i 20)(return i))
      (setq i (+ i 1))
      (if (= (mod i 15) 0)(print "FIZZ BUZZ")
          (if (= (mod i 3) 0)(print "FIZZ")
              (if (= (mod i 5) 0)(print "BUZZ")
                  (print i)
              )
          )
      )
)
